Add Macromill and Yahoo! JAPAN Ads, Tag Manager
patrickhulce/third-party-web pull request #136
Opened 2021-07-07 05:31 UTC by sisidovski

Hi!

I noticed `macromill.com` is treated as Yahoo! JAPAN's service, but actually Macromill is a marketing company, it's not related to Yahoo! JAPAN. In addition to that, today Yahoo! JAPAN is an independent company from Yahoo! US, they're running their own business. So I added ads and tag manager both provided by Yahoo! JAPAN to capture those 3Ps more precisely.

2021-07-07 15:17 UTC, patrickhulce requested changes
thanks very much @sisidovski this is great!

the examples are for examples of specific resources, not sites that use them :) but otherwise LGTM

2021-07-07 15:17 UTC, patrickhulce commented on data/entities.js
> +    examples: ['jp.moony.com/ja/home.html']
```suggestion
    examples: ['img.macromill.com/js/us000131vfg/4000000570-56/lognos.js']
```

2021-07-07 15:17 UTC, patrickhulce commented on data/entities.js
> +    examples: ['shopping.yahoo.co.jp'],
```suggestion
    examples: ['s.yimg.jp/images/ymstore/bnr/shp/paypay01/180_70.png'],
```

2021-07-07 15:17 UTC, patrickhulce commented on data/entities.js
> +    examples: ['www.yahoo.co.jp']
```suggestion
    examples: ['yjtag.yahoo.co.jp/tag?site=2wzBV9u']
```

2021-07-07 15:59 UTC, sisidovski commented
@patrickhulce Thank you so much! I changed example resources to the specific ones!

2021-07-07 16:06 UTC, patrickhulce approved these changes
thank you! 🎉

2021-07-07 16:29 UTC, patrickhulce commented
oh shoot sorry @sisidovski you'll need to update the snapshots for the tests :)

2021-07-08 01:29 UTC, sisidovski commented
@patrickhulce Updated!

2021-07-08 02:13 UTC, merged