142 generated queries rewritten
patrickhulce/third-party-web pull request #143
Opened 2021-08-02 18:19 UTC by christobill

2021-08-02 19:41 UTC, patrickhulce approved these changes

2021-08-02 19:42 UTC, patrickhulce requested changes
whoops, looks like not all the references to the removed template piece were removed. thanks for putting this up!

2021-08-02 23:08 UTC, christobill commented
Whoops indeed! @patrickhulce 

I wanted to remove `sql/bootup-time-scripting.partial.sql` but it looks like it was still used by:
- `sql/library-query.sql`
- `sql/url-query.sql
- `sql/total-time-query.sql`
- `sql/origin-per-page-query.sql`

I rollbacked `sql/bootup-time-scripting.partial.sql` removal
I migrated:
- `sql/total-time-query.sql`
- `sql/origin-per-page-query.sql`

And limited the query generation to /^(library-query|url-query).sql$/ so it doesn't create unnecessary `sql/*.generated.sql` files

Does that look ok to you? :smile:

2021-08-03 00:41 UTC, patrickhulce commented
> And limited the query generation to /^(library-query|url-query).sql$/ so it doesn't create unnecessary sql/*.generated.sql files

sounds like a plan! thanks so much!

2021-08-03 00:42 UTC, patrickhulce approved these changes

2021-08-03 00:42 UTC, merged